import statesData from './states.json';
import type { State, District, AllDistrictsData } from '@/types/location';

// Import districts data - will be generated by script
let districtsData: AllDistrictsData | null = null;

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  districtsData = require('../constants/all-districts.json') as AllDistrictsData;
} catch {
  // File doesn't exist yet, will be created by script
  console.warn('all-districts.json not found. Run scripts/fetch-districts.js to generate it.');
}

export const STATES: State[] = statesData.data;

/**
 * Get all states
 */
export function getStates(): State[] {
  return STATES;
}

/**
 * Get state by ID
 */
export function getStateById(stateId: string): State | undefined {
  return STATES.find((state) => state._id === stateId);
}

/**
 * Get state by name (case-insensitive)
 */
export function getStateByName(name: string): State | undefined {
  const normalizedName = name.toUpperCase().trim();
  return STATES.find((state) => state.name.toUpperCase() === normalizedName);
}

/**
 * Get all districts
 */
export function getAllDistricts(): District[] {
  return districtsData?.districts || [];
}

/**
 * Get districts by state ID
 */
export function getDistrictsByStateId(stateId: string): District[] {
  if (!districtsData) return [];
  return districtsData.data[stateId]?.districts || [];
}

/**
 * Get district by ID
 */
export function getDistrictById(districtId: string): District | undefined {
  if (!districtsData) return undefined;
  return districtsData.districts.find((district) => district._id === districtId);
}

/**
 * Get district by name and state ID (case-insensitive)
 */
export function getDistrictByName(districtName: string, stateId: string): District | undefined {
  const districts = getDistrictsByStateId(stateId);
  const normalizedName = districtName.toUpperCase().trim();
  return districts.find(
    (district) => district.name.toUpperCase() === normalizedName || district.name_en.toUpperCase() === normalizedName
  );
}

/**
 * Get default district for a state (usually the first one or the one with state name)
 */
export function getDefaultDistrictForState(stateId: string): District | undefined {
  const districts = getDistrictsByStateId(stateId);
  if (districts.length === 0) return undefined;

  // Try to find district with same name as state
  const state = getStateById(stateId);
  if (state) {
    const stateNameDistrict = districts.find(
      (d) => d.name.toUpperCase() === state.name.toUpperCase() || d.name_en.toUpperCase() === state.name_en.toUpperCase()
    );
    if (stateNameDistrict) return stateNameDistrict;
  }

  // Return first district
  return districts[0];
}

/**
 * Check if districts data is loaded
 */
export function isDistrictsDataLoaded(): boolean {
  return districtsData !== null;
}

